# Configuración General del Servidor
spring.application.name=logiflow
server.port=${PORT:8081}

# Activación de Hilos Virtuales
spring.threads.virtual.enabled=true

# Conexión a la Base de Datos
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5435/logiflow_db?rewriteBatchedStatements=true}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Pool de Conexiones HikariCP
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=5

# Configuración del ORM y Batching
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false 

# Habilitación de lotes
spring.jpa.properties.hibernate.jdbc.batch_size=500
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Configuración de Spring Batch
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false

# Permitir subida de archivos masivos
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB