# Configuración General del Servidor
spring.application.name=logiflow
server.port=8081

# Activación de Hilos Virtuales
spring.threads.virtual.enabled=true

# Conexión a la Base de Datos
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/logiflow_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración del ORM
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuración para la Demo
spring.batch.jdbc.initialize-schema=always